default: &default
  adapter: postgresql
  encoding: unicode
  pool: 200

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>